# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 5c4fd02
_src_path: gh:scipp/copier_template
description: Live data reduction visualisation framework for ESS.
max_python: '3.13'
min_python: '3.10'
namespace_package: ''
nightly_deps: scipp,sciline,plopp,essreduce
orgname: scipp
prettyname: Beamlime
projectname: beamlime
related_projects: Scipp,Sciline,Plopp,ESSreduce
year: 2025
