# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: bd89f40
_src_path: ../copier_template/
description: Live data reduction visualisation framework for ESS.
github_linux_image: ubuntu-20.04
max_python: '3.11'
min_python: '3.9'
orgname: scipp
projectname: beamlime
year: 2023
