# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 96938e6
_src_path: gh:scipp/copier_template
description: Live data reduction visualisation framework for ESS.
github_linux_image: ubuntu-20.04
max_python: '3.11'
min_python: '3.9'
orgname: scipp
projectname: beamlime
year: 2023
