name: beamlime-kafka
services:
  # Initialize kafka
  init-kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka-init
    # depends_on:
      # kafka:
      #   condition: service_healthy
    volumes:
      - ./scripts:/scripts
    command: ["sh", "/scripts/setup-kafka-topics.sh", "${BEAMLIME_INSTRUMENT:-nmx}"]

  detector-data:
    profiles:
      - detector
    image: python:3.12
    container_name: detector-data
    depends_on:
      init-kafka:
        condition: service_completed_successfully
      kafka:
        condition: service_healthy
    volumes:
      - .:/app
    working_dir: /app
    environment:
      BEAMLIME_ENV: docker
      BEAMLIME_INSTRUMENT: ${BEAMLIME_INSTRUMENT:-nmx}
      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS:-kafka:29092}
      KAFKA_SECURITY_PROTOCOL: ${KAFKA_SECURITY_PROTOCOL:-PLAINTEXT}
      KAFKA_SASL_MECHANISM: ${KAFKA_SASL_MECHANISM:-SCRAM-SHA-256}
      KAFKA_SASL_USERNAME: ${KAFKA_SASL_USERNAME:-DUMMY}
      KAFKA_SASL_PASSWORD: ${KAFKA_SASL_PASSWORD:-DUMMY}
      KAFKA2_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS:-kafka:29092}
      KAFKA2_SECURITY_PROTOCOL: ${KAFKA_SECURITY_PROTOCOL:-PLAINTEXT}
      KAFKA2_SASL_MECHANISM: ${KAFKA_SASL_MECHANISM:-SCRAM-SHA-256}
      KAFKA2_SASL_USERNAME: ${KAFKA_SASL_USERNAME:-DUMMY}
      KAFKA2_SASL_PASSWORD: ${KAFKA_SASL_PASSWORD:-DUMMY}
    command: sh -c "python -m pip install -e . && python -m beamlime.services.detector_data --instrument $BEAMLIME_INSTRUMENT"

  detector-dashboard:
    image: python:3.12
    container_name: detector-dashboard
    depends_on:
      init-kafka:
        condition: service_completed_successfully
      kafka:
        condition: service_healthy
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "5008:5008"
    environment:
      BEAMLIME_ENV: docker
      BEAMLIME_INSTRUMENT: ${BEAMLIME_INSTRUMENT:-nmx}
      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS:-kafka:29092}
      KAFKA_SECURITY_PROTOCOL: ${KAFKA_SECURITY_PROTOCOL:-PLAINTEXT}
      KAFKA_SASL_MECHANISM: ${KAFKA_SASL_MECHANISM:-SCRAM-SHA-256}
      KAFKA_SASL_USERNAME: ${KAFKA_SASL_USERNAME:-DUMMY}
      KAFKA_SASL_PASSWORD: ${KAFKA_SASL_PASSWORD:-DUMMY}
      KAFKA2_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS:-kafka:29092}
      KAFKA2_SECURITY_PROTOCOL: ${KAFKA_SECURITY_PROTOCOL:-PLAINTEXT}
      KAFKA2_SASL_MECHANISM: ${KAFKA_SASL_MECHANISM:-SCRAM-SHA-256}
      KAFKA2_SASL_USERNAME: ${KAFKA_SASL_USERNAME:-DUMMY}
      KAFKA2_SASL_PASSWORD: ${KAFKA_SASL_PASSWORD:-DUMMY}
    command: sh -c "python -m pip install -e .[dashboard] && gunicorn beamlime.dashboard.detectors_wsgi:application -b 0.0.0.0:5008"
