import scipp as sc

_res_scale = 8
pixel_noise = sc.scalar(4.0, unit='mm')

detectors_config = {
    'detectors': {
        'Channel (1, 1)': {
            'detector_name': '123_channel_1_1_triplet',
            'resolution': {'y': 30 * _res_scale, 'x': 20 * _res_scale},
            'projection': 'xy_plane',
            'pixel_noise': pixel_noise,
        },
        'Channel (1, 2)': {
            'detector_name': '127_channel_1_2_triplet',
            'resolution': {'y': 30 * _res_scale, 'x': 20 * _res_scale},
            'projection': 'xy_plane',
            'pixel_noise': pixel_noise,
        },
        'Channel (1, 3)': {
            'detector_name': '131_channel_1_3_triplet',
            'resolution': {'y': 30 * _res_scale, 'x': 20 * _res_scale},
            'projection': 'xy_plane',
            'pixel_noise': pixel_noise,
        },
        'Channel (1, 4)': {
            'detector_name': '135_channel_1_4_triplet',
            'resolution': {'y': 30 * _res_scale, 'x': 20 * _res_scale},
            'projection': 'xy_plane',
            'pixel_noise': pixel_noise,
        },
        'Channel (1, 5)': {
            'detector_name': '139_channel_1_5_triplet',
            'resolution': {'y': 30 * _res_scale, 'x': 20 * _res_scale},
            'projection': 'xy_plane',
            'pixel_noise': pixel_noise,
        },
        'Channel (2, 1)': {
            'detector_name': '144_channel_2_1_triplet',
            'resolution': {'y': 30 * _res_scale, 'x': 20 * _res_scale},
            'projection': 'xy_plane',
            'pixel_noise': pixel_noise,
        },
        'Channel (2, 2)': {
            'detector_name': '148_channel_2_2_triplet',
            'resolution': {'y': 30 * _res_scale, 'x': 20 * _res_scale},
            'projection': 'xy_plane',
            'pixel_noise': pixel_noise,
        },
        'Channel (2, 3)': {
            'detector_name': '152_channel_2_3_triplet',
            'resolution': {'y': 30 * _res_scale, 'x': 20 * _res_scale},
            'projection': 'xy_plane',
            'pixel_noise': pixel_noise,
        },
        'Channel (2, 4)': {
            'detector_name': '156_channel_2_4_triplet',
            'resolution': {'y': 30 * _res_scale, 'x': 20 * _res_scale},
            'projection': 'xy_plane',
            'pixel_noise': pixel_noise,
        },
        'Channel (2, 5)': {
            'detector_name': '160_channel_2_5_triplet',
            'resolution': {'y': 30 * _res_scale, 'x': 20 * _res_scale},
            'projection': 'xy_plane',
            'pixel_noise': pixel_noise,
        },
        'Channel (3, 1)': {
            'detector_name': '165_channel_3_1_triplet',
            'resolution': {'y': 30 * _res_scale, 'x': 20 * _res_scale},
            'projection': 'xy_plane',
            'pixel_noise': pixel_noise,
        },
        'Channel (3, 2)': {
            'detector_name': '169_channel_3_2_triplet',
            'resolution': {'y': 30 * _res_scale, 'x': 20 * _res_scale},
            'projection': 'xy_plane',
            'pixel_noise': pixel_noise,
        },
        'Channel (3, 3)': {
            'detector_name': '173_channel_3_3_triplet',
            'resolution': {'y': 30 * _res_scale, 'x': 20 * _res_scale},
            'projection': 'xy_plane',
            'pixel_noise': pixel_noise,
        },
        'Channel (3, 4)': {
            'detector_name': '177_channel_3_4_triplet',
            'resolution': {'y': 30 * _res_scale, 'x': 20 * _res_scale},
            'projection': 'xy_plane',
            'pixel_noise': pixel_noise,
        },
        'Channel (3, 5)': {
            'detector_name': '181_channel_3_5_triplet',
            'resolution': {'y': 30 * _res_scale, 'x': 20 * _res_scale},
            'projection': 'xy_plane',
            'pixel_noise': pixel_noise,
        },
        'Channel (4, 1)': {
            'detector_name': '186_channel_4_1_triplet',
            'resolution': {'y': 30 * _res_scale, 'x': 20 * _res_scale},
            'projection': 'xy_plane',
            'pixel_noise': pixel_noise,
        },
        'Channel (4, 2)': {
            'detector_name': '190_channel_4_2_triplet',
            'resolution': {'y': 30 * _res_scale, 'x': 20 * _res_scale},
            'projection': 'xy_plane',
            'pixel_noise': pixel_noise,
        },
        'Channel (4, 3)': {
            'detector_name': '194_channel_4_3_triplet',
            'resolution': {'y': 30 * _res_scale, 'x': 20 * _res_scale},
            'projection': 'xy_plane',
            'pixel_noise': pixel_noise,
        },
        'Channel (4, 4)': {
            'detector_name': '198_channel_4_4_triplet',
            'resolution': {'y': 30 * _res_scale, 'x': 20 * _res_scale},
            'projection': 'xy_plane',
            'pixel_noise': pixel_noise,
        },
        'Channel (4, 5)': {
            'detector_name': '202_channel_4_5_triplet',
            'resolution': {'y': 30 * _res_scale, 'x': 20 * _res_scale},
            'projection': 'xy_plane',
            'pixel_noise': pixel_noise,
        },
        'Channel (5, 1)': {
            'detector_name': '207_channel_5_1_triplet',
            'resolution': {'y': 30 * _res_scale, 'x': 20 * _res_scale},
            'projection': 'xy_plane',
            'pixel_noise': pixel_noise,
        },
        'Channel (5, 2)': {
            'detector_name': '211_channel_5_2_triplet',
            'resolution': {'y': 30 * _res_scale, 'x': 20 * _res_scale},
            'projection': 'xy_plane',
            'pixel_noise': pixel_noise,
        },
        'Channel (5, 3)': {
            'detector_name': '215_channel_5_3_triplet',
            'resolution': {'y': 30 * _res_scale, 'x': 20 * _res_scale},
            'projection': 'xy_plane',
            'pixel_noise': pixel_noise,
        },
        'Channel (5, 4)': {
            'detector_name': '219_channel_5_4_triplet',
            'resolution': {'y': 30 * _res_scale, 'x': 20 * _res_scale},
            'projection': 'xy_plane',
            'pixel_noise': pixel_noise,
        },
        'Channel (5, 5)': {
            'detector_name': '223_channel_5_5_triplet',
            'resolution': {'y': 30 * _res_scale, 'x': 20 * _res_scale},
            'projection': 'xy_plane',
            'pixel_noise': pixel_noise,
        },
        'Channel (6, 1)': {
            'detector_name': '228_channel_6_1_triplet',
            'resolution': {'y': 30 * _res_scale, 'x': 20 * _res_scale},
            'projection': 'xy_plane',
            'pixel_noise': pixel_noise,
        },
        'Channel (6, 2)': {
            'detector_name': '232_channel_6_2_triplet',
            'resolution': {'y': 30 * _res_scale, 'x': 20 * _res_scale},
            'projection': 'xy_plane',
            'pixel_noise': pixel_noise,
        },
        'Channel (6, 3)': {
            'detector_name': '236_channel_6_3_triplet',
            'resolution': {'y': 30 * _res_scale, 'x': 20 * _res_scale},
            'projection': 'xy_plane',
            'pixel_noise': pixel_noise,
        },
        'Channel (6, 4)': {
            'detector_name': '240_channel_6_4_triplet',
            'resolution': {'y': 30 * _res_scale, 'x': 20 * _res_scale},
            'projection': 'xy_plane',
            'pixel_noise': pixel_noise,
        },
        'Channel (6, 5)': {
            'detector_name': '244_channel_6_5_triplet',
            'resolution': {'y': 30 * _res_scale, 'x': 20 * _res_scale},
            'projection': 'xy_plane',
            'pixel_noise': pixel_noise,
        },
        'Channel (7, 1)': {
            'detector_name': '249_channel_7_1_triplet',
            'resolution': {'y': 30 * _res_scale, 'x': 20 * _res_scale},
            'projection': 'xy_plane',
            'pixel_noise': pixel_noise,
        },
        'Channel (7, 2)': {
            'detector_name': '253_channel_7_2_triplet',
            'resolution': {'y': 30 * _res_scale, 'x': 20 * _res_scale},
            'projection': 'xy_plane',
            'pixel_noise': pixel_noise,
        },
        'Channel (7, 3)': {
            'detector_name': '257_channel_7_3_triplet',
            'resolution': {'y': 30 * _res_scale, 'x': 20 * _res_scale},
            'projection': 'xy_plane',
            'pixel_noise': pixel_noise,
        },
        'Channel (7, 4)': {
            'detector_name': '261_channel_7_4_triplet',
            'resolution': {'y': 30 * _res_scale, 'x': 20 * _res_scale},
            'projection': 'xy_plane',
            'pixel_noise': pixel_noise,
        },
        'Channel (7, 5)': {
            'detector_name': '265_channel_7_5_triplet',
            'resolution': {'y': 30 * _res_scale, 'x': 20 * _res_scale},
            'projection': 'xy_plane',
            'pixel_noise': pixel_noise,
        },
        'Channel (8, 1)': {
            'detector_name': '270_channel_8_1_triplet',
            'resolution': {'y': 30 * _res_scale, 'x': 20 * _res_scale},
            'projection': 'xy_plane',
            'pixel_noise': pixel_noise,
        },
        'Channel (8, 2)': {
            'detector_name': '274_channel_8_2_triplet',
            'resolution': {'y': 30 * _res_scale, 'x': 20 * _res_scale},
            'projection': 'xy_plane',
            'pixel_noise': pixel_noise,
        },
        'Channel (8, 3)': {
            'detector_name': '278_channel_8_3_triplet',
            'resolution': {'y': 30 * _res_scale, 'x': 20 * _res_scale},
            'projection': 'xy_plane',
            'pixel_noise': pixel_noise,
        },
        'Channel (8, 4)': {
            'detector_name': '282_channel_8_4_triplet',
            'resolution': {'y': 30 * _res_scale, 'x': 20 * _res_scale},
            'projection': 'xy_plane',
            'pixel_noise': pixel_noise,
        },
        'Channel (8, 5)': {
            'detector_name': '286_channel_8_5_triplet',
            'resolution': {'y': 30 * _res_scale, 'x': 20 * _res_scale},
            'projection': 'xy_plane',
            'pixel_noise': pixel_noise,
        },
        'Channel (9, 1)': {
            'detector_name': '291_channel_9_1_triplet',
            'resolution': {'y': 30 * _res_scale, 'x': 20 * _res_scale},
            'projection': 'xy_plane',
            'pixel_noise': pixel_noise,
        },
        'Channel (9, 2)': {
            'detector_name': '295_channel_9_2_triplet',
            'resolution': {'y': 30 * _res_scale, 'x': 20 * _res_scale},
            'projection': 'xy_plane',
            'pixel_noise': pixel_noise,
        },
        'Channel (9, 3)': {
            'detector_name': '299_channel_9_3_triplet',
            'resolution': {'y': 30 * _res_scale, 'x': 20 * _res_scale},
            'projection': 'xy_plane',
            'pixel_noise': pixel_noise,
        },
        'Channel (9, 4)': {
            'detector_name': '303_channel_9_4_triplet',
            'resolution': {'y': 30 * _res_scale, 'x': 20 * _res_scale},
            'projection': 'xy_plane',
            'pixel_noise': pixel_noise,
        },
        'Channel (9, 5)': {
            'detector_name': '307_channel_9_5_triplet',
            'resolution': {'y': 30 * _res_scale, 'x': 20 * _res_scale},
            'projection': 'xy_plane',
            'pixel_noise': pixel_noise,
        },
    },
}
