services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: kafka-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka-broker
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      # Disk usage limits
      KAFKA_LOG_RETENTION_BYTES: 1073741824  # 1GB total retention
      KAFKA_LOG_RETENTION_HOURS: 1           # Keep logs for 1 hours
      KAFKA_LOG_SEGMENT_BYTES: 268435456     # 256MB per segment
      KAFKA_LOG_CLEANUP_POLICY: delete       # Delete old segments
      KAFKA_LOG_CLEANER_MIN_CLEANABLE_RATIO: 0.5
      KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS: 120000  # Check every 2 minutes