auto.offset.reset: latest
enable.auto.commit: true
fetch.min.bytes: 1
fetch.max.bytes: 200000000  # might need at least 10x this in RAM for processing
session.timeout.ms: 30000
heartbeat.interval.ms: 10000  # long so we do not timeout when processing large data