package:
  name: beamlime

  version: {{ GIT_DESCRIBE_TAG }}

source:
  path: ..

requirements:
  build:
    - setuptools
    - setuptools_scm
  run:
    - rich
    - python>=3.10

test:
  imports:
    - beamlime
  requires:
    - pytest
    - numpy
    - scipp
    - plopp
    - sciline
    - scippneutron
  source_files:
    - pyproject.toml
    - tests/
  commands:
    # We ignore warnings during release package builds
    - python -m pytest -Wignore tests

build:
  noarch: python
  script:
    - python -m pip install .

about:
  home: https://github.com/scipp/beamlime
  license: BSD-3-Clause
  summary: Live data reduction visualisation framework for ESS.
  description: Live data reduction visualisation framework for ESS.
  dev_url: https://github.com/scipp/beamlime
  doc_url: https://scipp.github.io/beamlime
