
name: CI

on:
  push:
    branches:
      - main
      - release
  pull_request:

jobs:
  formatting:
    name: Formatting and static analysis
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - run: python -m pip install --upgrade pip
      - run: python -m pip install -r requirements/ci.txt
      - run: tox -e static
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply automatic formatting

  tests:
    name: Tests
    needs: formatting
    uses: ./.github/workflows/test.yml
    with:
      os-variant: ["ubuntu-20.04"]
      # os-variant: ["ubuntu-20.04", "macos-11", "windows-2019"]
      # TODO: Decide if we are going to support MacOS and Windows or not.
      # Other OSs are tested in the Optional action.
      python-version-variant: ["3.9", "3.10", "3.11"]

  docs:
    name: Test document build
    needs: tests
    uses: ./.github/workflows/docs.yml
    with:
      publish: false
      version: ${{ github.ref_name }}
      branch: ${{ github.head_ref == '' && github.ref_name || github.head_ref }}
