
name: Manual Docs

on:
  workflow_dispatch:
    inputs:
      publish:
        default: false
        type: boolean
      version:
        default: ''
        required: false
        type: string
      branch:
        description: 'Branch/tag with documentation source. If not set, the current branch will be used.'
        default: ''
        required: false
        type: string

env:
  VERSION: ${{ inputs.version }}

jobs:
  docs:
    uses: ./.github/workflows/docs.yml
    with:
      publish: ${{ inputs.publish }}
      version: ${{ inputs.version }}
      branch: ${{ inputs.branch }}
