
name: Optional

on:
  push:
    branches:
      - main
      - release
  pull_request:

jobs:
  tests:
    name: Tests ${{ matrix.os }} py${{ matrix.python }}
    strategy:
      matrix:
        os: ["macos-11", "windows-2019"]
        py:
          - python: "3.9"
            tox-env: "py39"
          - python: "3.10"
            tox-env: "py310"
          - python: "3.11"
            tox-env: "py311"

    uses: ./.github/workflows/test.yml
    with:
      os-variant: ${{ matrix.os }}
      python-version: ${{ matrix.py.python }}
      tox-env: ${{ matrix.py.tox-env }}
