
name: Optional

on:
  push:
    branches:
      - main
      - release
  pull_request:

jobs:
  tests:
    name: Tests
    uses: ./.github/workflows/test.yml
    with:
      os-variant: ["macos-11", "windows-2019"]
      python-version-variant: ["3.9", "3.10", "3.11"]
