# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2023 Scipp contributors (https://github.com/scipp)

name: CI

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref == 'refs/heads/main' && github.run_number || github.ref }}
  cancel-in-progress: true  # cancel jobs from previous push

jobs:
  formatting:
    uses: ./.github/workflows/reusable-static.yml

  single-test:
    needs: formatting
    uses: ./.github/workflows/reusable-test.yml
    with:
      coverage-report: true