# Copyright (c) 2023 Scipp contributors (https://github.com/scipp)

name: CI Environment Setup

on:
  workflow_call:
    inputs:
      os-variant:
        default: 'ubuntu-20.04'
        type: string
    env-file:
      default: 'ci.txt'
      type: string
    python-version:
      default: '3.9'
      type: string
    branch:
      description: 'Branch/tag with documentation source. If not set, the current branch will be used.'
      default: ''
      required: false
      type: string

jobs:
  setup-python-39:
    runs-on: ${{ inputs.os-variant }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.branch == '' && github.ref_name || inputs.branch }}
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ inputs.python-version }}
      - run: python -m pip install --upgrade pip
      - run: python -m pip install -r requirements/${{ inputs.env-file }}
