# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2023 Scipp contributors (https://github.com/scipp)

name: Test

on:
  workflow_dispatch:
    inputs:
      os-variant:
        default: ['ubuntu-20.04']
        type: list
      python-version-variant:
        default: ['3.9']
        type: list
      tox-env-variant:
        default: ['test']
        type: list
      pip-recipe:
        default: 'requirements/ci.txt'
        type: string
      coverage-report:
        default: false
        type: boolean
  workflow_call:
    inputs:
      os-variant:
        default: ['ubuntu-20.04']
        type: list
      python-version-variant:
        default: ['3.9']
        type: list
      tox-env-variant:
        default: ['test']
        type: list
      pip-recipe:
        default: 'requirements/ci.txt'
        type: string
      coverage-report:
        default: false
        type: boolean

jobs:
  test:
    name: tests ${{ matrix.os }}, py${{ matrix.python }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ${{ inputs.os-variant }}
        python-version: ${{ inputs.python-version-variant }}
        tox-env: ${{ inputs.tox-env-variant }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - run: python -m pip install --upgrade pip
      - run: python -m pip install -r ${{ inputs.pip-recipe }}
      - run: tox -e ${{ matrix.tox-env }}
      - uses: actions/upload-artifact@v3
        if: ${{ inputs.coverage-report }}
        with:
          name: CoverageReport
          path: coverage_html/
